apiVersion: apps/v1
kind: Deployment

metadata:
  name: student-counter

spec:
  replicas: 2

  selector:
    matchLabels:
      app: student-counter

  template:
    metadata:
      labels:
        app: student-counter

    spec:
      containers:
      - name: student-counter
        image: ghcr.io/bhoomikabn/student-counter:latest
        ports:
        - containerPort: 3000